achorein/expo-share-intent

README.md, plugin/src/ios/writeIosShareExtensionFiles.ts
**Summary**
The share intent does not work without a correct custom url scheme. The build should not succeeded in that case.
**Todo**
**Issue**
- https://github.com/achorein/expo-share-intent/issues/1
=> fix: custom url scheme is mandatory

android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt
**Summary**
```console
> Task :app:processDebugMainManifest
/project/expo-share-intent/expo-share-intent-plugin/example/basic/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
/project/expo-share-intent/expo-share-intent-plugin/example/basic/android/app/src/debug/AndroidManifest.xml Warning:
provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
> Task :expo-share-intent:compileDebugKotlin
w: file:///project/expo-share-intent/expo-share-intent-plugin/android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt:77:4 …
```
=> fix: Android build warnings

android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt
**Summary**
Fix the error occurring on device Android 10 (SDK 29) :
```java
Exception java.lang.NullPointerException:
at expo.modules.shareintent.ExpoShareIntentModule$Companion.handleShareIntent (ExpoShareIntentModule.kt:64)
at expo.modules.shareintent.ExpoShareIntentModule$definition$lambda$4$$inlined$OnNewIntent$1.invoke (ModuleDefinitionBuilder.kt:144)
at expo.modules.shareintent.ExpoShareIntentModule$definition$lambda$4$$inlined$OnNewIntent$1.invoke (ModuleDefinitionBuilder.kt:117)
at expo.modules.kotlin.events.EventListenerWithPayload.call (EventListener.kt:25)
at expo.modules.kotlin.ModuleHolder.post (ModuleHolder.kt:100)
at expo.modules.kotlin.ModuleRegistry.post (ModuleRegistry.kt:94)
at expo.modules.kotlin.AppContext.onNewIntent$expo_modules_core_release (AppContext.kt:350)
at …
```
=> fix: android intent type null on android 10

android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt, example/basic/package.json, example/basic/yarn.lock, example/expo-router/package.json, example/expo-router/yarn.lock, ios/ExpoShareIntentModule.swift, plugin/src/ios/ShareExtensionViewController.swift, src/ExpoShareIntentModule.ts, src/index.ts, src/useShareIntent.tsx
**Summary**
Force ios cleanup of share intent when going to background.
**Todo**
**Issue**
https://github.com/achorein/expo-share-intent/issues/14
=> fix: not reset when going to background on ios

example/basic/App.tsx, example/expo-router/app/_layout.js, src/ExpoShareIntentModule.types.ts, src/useShareIntent.tsx
**Summary**
After a share intent, by default when the app is going into background the share intent is reset.
This PR add the possibility to disable this behaviour
```ts
const { shareIntent } = useShareIntent({ resetOnBackground: false });
```
**Todo**
=> feat: add resetOnBackground option

README.md, src/ShareIntentProvider.tsx, src/index.ts
**Summary**
Add a context provider to persist sharing intent over multiple screen or when dealing with multiple third party provider.
**Issue**
https://github.com/achorein/expo-share-intent/issues/15
=> feat: Add ShareIntentProvider

.gitignore, android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt, android/src/main/java/expo/modules/shareintent/ExpoShareIntentReactActivityLifecycleListener.kt, android/src/main/java/expo/modules/shareintent/ExpoShareIntentSingleton.kt, ios/ExpoShareIntentModule.swift, src/ExpoShareIntentModule.ts, src/ExpoShareIntentModule.types.ts, src/ShareIntentProvider.tsx, src/index.ts, src/useShareIntent.tsx
**Summary**
```ts
import { ShareIntentProvider, useShareIntentContext, hasShareIntent, addStateListener } from "expo-share-intent";
```
**Todo**
```ts
onResetShareIntent: () => navigationRef.current?.navigate("Home"),
```
```ts
const shareIntentEventSubscription = addStateListener((event) => {
if (event.value === "pending") {
// Go to screen with useShareIntent hook
}
});
```
**Test**
=> feat: add share intent state management

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr.yml, example/basic/package.json, example/basic/yarn.lock, example/expo-router/package.json, example/expo-router/yarn.lock, example/react-navigation/package.json, example/react-navigation/yarn.lock, src/ExpoShareIntentModule.ts, src/useShareIntent.tsx
**Summary**
**Todo**
**Issue**
https://github.com/achorein/expo-share-intent/issues/26
=> fix: crash on background when reseting native module

README.md, package.json, plugin/src/index.ts, plugin/src/withCompatibilityChecker.ts, plugin/tsconfig.json
**Summary**
Simply add a warning message for incompatibility with expo SDK
```bach
$ expo prebuild --no-install
» android: expo-share-intent: your Expo SDK version does not match requirements ! v1.1.1 needs ^50, found 49.0.0. Please refer to the compatibility table. https://github.com/achorein/expo-share-intent/#versioning
```
**Todo**
=> fix: add incompatibility checker on prebuild

README.md, android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt, ios/ExpoShareIntentModule.swift, plugin/src/ios/ShareExtensionViewController.swift, plugin/src/types.ts, src/ExpoShareIntentModule.types.ts, src/useShareIntent.tsx
**Summary**
**Todo**
**Issue**
https://github.com/achorein/expo-share-intent/issues/25
**Test**
=> feat: retrieve file type, file name and auto detect link in a text shareintent

README.md, plugin/src/withCompatibilityChecker.ts
**Summary**
When using `@react-native-google-signin/google-signin` we need to configure a custom scheme in our app.json to handle google signin fallback. By doing this, the original app scheme is deleted and must be manually reassigned.
This PR add compatibilty check to drive new comers
**Todo**
**Issue**
- https://github.com/achorein/expo-share-intent-demo/issues/19
- https://github.com/achorein/expo-share-intent/issues/35
Thanks to @magnum6actual ! 🙏
=> fix: Check compatibilty with scheme and CFBundleURLSchemes

README.md, ios/ExpoShareIntentModule.swift, plugin/src/ios/ShareExtensionViewController.swift, src/ExpoShareIntentModule.types.ts, src/useShareIntent.tsx
**Summary**
In order to have the same file description on iOS and Android, we need to get the mimeType from the iOS part.
```js
export interface IosShareIntentFile {
path: string;
type: string;
fileName: string;
mimeType: string;
}
export interface AndroidShareIntentFile {
fileName: string;
filePath: string;
mimeType: string;
contentUri: string;
}
```
**Todo**
**Issue**
https://github.com/achorein/expo-share-intent/issues/40
=> feat: retreive file mimeType from iOS

README.md, android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt, ios/ExpoShareIntentModule.swift, plugin/src/ios/ShareExtensionViewController.swift, src/ExpoShareIntentModule.types.ts, src/useShareIntent.tsx
**Summary**
In order to know if we have to resize the given file (media like images), this PR add the shared file size in octets.
```js
export interface ShareIntentFile {
path: string;
mimeType: string;
fileName: string;
size: number | null;
}
```
**Todo**
**Issue**
https://github.com/achorein/expo-share-intent/issues/34
https://github.com/achorein/expo-share-intent/issues/40
=> feat: retreive file size

example/basic/App.tsx, example/basic/package.json, example/basic/yarn.lock, example/expo-router/package.json, example/expo-router/yarn.lock, example/react-navigation/app/Navigator.tsx, example/react-navigation/package.json, example/react-navigation/yarn.lock, src/ExpoShareIntentModule.ts, src/ExpoShareIntentModule.types.ts, src/index.ts, src/useShareIntent.tsx, src/utils.ts
**Summary**
When using `expo-updates` in a release build, sometimes the scheme is no availaible in the runtime (`Constants.expoConfig?.scheme`)
similar issue : `https://github.com/expo/custom-expo-updates-server/issues/12`
**Todo**
```js
useShareIntent({
scheme: "exposhareintentexample",
});
```
```jsx
<ShareIntentProvider
options={{
scheme: "exposhareintentexample",
}}
>
```
**Issue**
https://github.com/achorein/expo-share-intent/issues/46
**Testing**
https://docs.expo.dev/eas-update/debug-advanced/#ios-local-builds
```
yarn ios ---configuration Release
```
=> fix: missing scheme on runtime when using expo-updates

plugin/src/ios/withIosShareExtensionXcodeTarget.ts, plugin/src/ios/writeIosShareExtensionFiles.ts
**Summary**
>ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/ShareExtension.appex/ShareExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
Related to …
=> fix: handle ios privacy manifest

src/ExpoShareIntentModule.types.ts, src/useShareIntent.tsx, tsconfig.json
**Summary**
This is my first PR to an open source project ever, so feel free to shoot down. 
1. Added descriptions to some of the types
2. Created a common type between them in some instances
3. Added some additional TSConfig rules used in some big open source projects
4. Removed all the Typescript warnings within useShareIntent.
Trying to keep this PR small and management because I'm still learning. Feel free to shut down this PR.
**Todo**
I added some TODO text to the types that eventually would be ideal to clean up and get one common type. I'm not bold enough to mess with the native code yet.
**Issue**
No Github issues. Just trying to add some comments and be helpful.
=> refactor: clean TS errors, add TS rules, cmn types

android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt, example/basic/App.tsx
**Summary**
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/33
=> fix: android exception on multiple files sharing

ios/ExpoShareIntentModule.swift, src/useShareIntent.tsx
**Summary**
Use JSON Encoding when sharing text on iOS.
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/55
=> fix: text parsing on ios

package.json, yarn.lock
**Summary**
I'm seeing a warning when I run npx expo-doctor: Expected package @expo/config-plugins@~8.0.0 (found 7.9.2)
The version of `@expo/config-plugins` was updated to 8.0.0 in 2.0.1 but I'm still seeing the 7.9.2 warning so I've been looking into where that version is coming from.
I think it could be `expo-linking` and `expo-constants`:
'''
=> Found "expo-share-intent#@expo/config#@expo/config-plugins@7.9.2"
info This module exists because "expo-share-intent#expo-constants#@expo#config" depends on it.
=> Found "expo-linking#@expo/config-plugins@7.9.2"
info Reasons this module exists
- "expo-share-intent#expo-linking#expo-constants#@expo#config" depends on it
- Hoisted from "expo-share-intent#expo-linking#expo-constants#@expo#config#@expo#config-plugins"
'''
Looking at npm it seems …
=> chore: Update versions of `expo-linking` and `expo-constants`

example/basic/package.json, example/basic/yarn.lock, example/expo-router/package.json, example/expo-router/yarn.lock, example/react-navigation/package.json, example/react-navigation/yarn.lock, plugin/src/ios/writeIosShareExtensionFiles.ts, src/utils.ts
**Summary**
The plugin does not handle multiple schemes defined in the `app.json` file https://docs.expo.dev/versions/latest/config/app/#scheme.
This PR manage to use the first scheme when giving an array.
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/64
=> feat: handle multiple scheme (ios)

plugin/src/ios/withIosShareExtensionXcodeTarget.ts, plugin/src/ios/writeIosShareExtensionFiles.ts
**Summary**
MacOS share extension called "Share Extension" instead of app name
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/39
=> fix: ios share extension name

android/build.gradle
**Summary**
A warning appears on a manual `pod install` in `ios/` folder (not using expo run process to install pods)
**Todo**
Related to https://github.com/achorein/expo-share-intent/pull/59
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/68
=> fix: gradle warning on podinstall

plugin/src/ios/ShareExtensionViewController.swift
**Summary**
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/98
=> fix: ios handle sharing a text file

plugin/src/ios/withIosShareExtensionConfig.ts
**Summary**
This fixes building issue when `appExtensions` is non-empty. `extConfigIndex` must be set to the last index after appending new entitlement
**Issue** https://github.com/achorein/expo-share-intent/issues/32
=> fix: correct config index

android/src/main/java/expo/modules/shareintent/ExpoShareIntentModule.kt
**Summary**
It seemed to be a failure to get ContentResolver.
On real device, it seems like the currentActivity is destroyed when the app goes into the background.
**Todo**
**Issue**
fixes https://github.com/achorein/expo-share-intent/issues/91
=> fix: android current activity null

plugin/src/ios/withIosShareExtensionXcodeTarget.ts
**Summary**
Every time I run `npx expo prebuild`, a duplicate target is added on the xcode main project. This is wrong and causes build failures.
This PR adds checks to skip the process if the target was previously added to the main project.
=> fix: ios - ensure the target is not added to main project multiple times (during prebuild)

plugin/src/ios/constants.ts, plugin/src/ios/withIosShareExtensionConfig.ts, plugin/src/ios/withIosShareExtensionXcodeTarget.ts
**Summary**
```sh
✖ Prebuild failed
Error: [ios.xcodeproj]: withIosXcodeprojBaseMod: [expo-share-intent] Could not add resource files to the Share Extension, please check your "patch-package" installation for xcode (see: https://github.com/achorein/expo-share-intent?tab=readme-ov-file#installation)
```
**Todo**
**Issue**
=> fix: add explicit error message for patch-package requirement

android/build.gradle, android/src/main/java/expo/modules/shareintent/ExpoShareIntentReactActivityLifecycleListener.kt
**Summary**
on android when a share was made while the application was not running, the “share intent” was not available because it was overwritten by a new activity
**Issue**
No issue
=> fix: android intent is overrided on firstlaunch

plugin/src/android/withAndroidIntentFilters.ts, plugin/src/ios/withIosShareExtensionConfig.ts, plugin/src/ios/writeIosShareExtensionFiles.ts
When Expo creates the config JSON dynamically, it seems that stdout outputs are taken into account. To avoid messing up the JSON, all debug prints should go to stderr. This PR does so by replacing `console.debug` with `console.warn`, fixing #157. Unfortunately, it does not fix #159.
=> fix: replaced console.debug with console.warn to avoid printing to stdout

plugin/src/ios/ShareExtensionViewController.swift
**Summary**
These changes allow the Share Extension to reliably detect, handle, and process .pkpass files shared to the app—such as boarding passes, event tickets, or coupons from Apple Wallet. It enhances the module's flexibility and aligns with modern iOS capabilities.
Add pkpass UTI Constant
Extend File Handling Logic
Handle pkpass method
Update Extension Logic to Recognize .pkpass Files by Name
**Todo**
**Issue**
Fixes https://github.com/achorein/expo-share-intent/issues/169
=> feat: add support for pkpass MIME type (iOS)
